const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let state={portfolio:null,runtime:null,orders:[],logs:[],opportunities:[],rnd:[],session:null};
async function getJSON(path,fallback){try{const r=await fetch(path+'?v='+Date.now());if(!r.ok)throw Error(r.status);return await r.json()}catch(e){return fallback}}
function money(v){return Number(v||0).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2})}
function positionValue(p){return Number(p.qty)*Number(p.price)}
function pnl(p){return Number(p.qty)*(Number(p.price)-Number(p.avg))}
function pct(p){return Number(p.avg)?((Number(p.price)/Number(p.avg))-1)*100:0}
function totalAssets(){return state.portfolio.cash+state.portfolio.positions.reduce((a,p)=>a+positionValue(p),0)}
function concentration(p){return totalAssets()?positionValue(p)/totalAssets()*100:0}
function riskScore(p){let s=22;if(concentration(p)>25)s+=28;if(pct(p)<-20)s+=24;if((p.role||'').includes('تخارج'))s+=18;if((p.account||'').includes('Private'))s+=8;return Math.min(100,Math.round(s))}
function healthScore(p){return Math.max(0,Math.min(100,Math.round(82-(riskScore(p)*.35)+(pct(p)*.35))))}
function opportunityScore(p){let s=58;if((p.role||'').includes('يورانيوم'))s+=12;if(pct(p)>0)s+=6;if(riskScore(p)>70)s-=22;return Math.max(0,Math.min(100,Math.round(s)))}
function cei(p){return Math.max(0,Math.min(100,Math.round(opportunityScore(p)*.55+healthScore(p)*.35-riskScore(p)*.20+20)))}
function decision(p){if((p.role||'').includes('تخارج'))return{label:'تخفيف مشروط / لا زيادة',cls:'amber'};if(concentration(p)>35)return{label:'خفض التركّز قبل التعزيز',cls:'red'};if(riskScore(p)>68)return{label:'مراجعة دفاعية',cls:'red'};if(cei(p)>72)return{label:'احتفاظ مشروط عالي الكفاءة',cls:'green'};return{label:'احتفاظ ومراقبة',cls:'cyan'}}
function log(msg,cls=''){state.logs.push({msg,cls,time:new Date().toLocaleTimeString('ar-SA')});$('#log').innerHTML=state.logs.map(x=>`<div class="${x.cls}">[${x.time}] ${x.msg}</div>`).join('');$('#log').scrollTop=99999}
async function loadData(){
 const fallbackP={snapshot_date:'2026-07-12',cash:3970,confirmed_transfer:3970,positions:[],watchlist:[{symbol:'UEC',reason:'تم البيع'}],portfolio_memory:[{symbol:'UEC',event:'EXITED'}]};
 const fallbackR={managers:[{id:'RND',name:'مدير الأبحاث والتطوير'},{id:'OPP',name:'مدير الفرص'},{id:'RISK',name:'مدير المخاطر'},{id:'CAP',name:'مدير رأس المال'},{id:'AUDIT',name:'مدير التدقيق والجودة'},{id:'CEO',name:'CEO AI'}]};
 state.portfolio=await getJSON('data/portfolio.json',fallbackP);state.runtime=await getJSON('data/board_runtime.json',fallbackR);renderAll();
}
function renderAll(){renderMetrics();renderPortfolio();renderClassifications();renderManagers();renderCapital();renderOrders();renderResearch()}
function renderMetrics(){const invested=state.portfolio.positions.reduce((a,p)=>a+positionValue(p),0),total=totalAssets();$('#total').textContent=money(total);$('#cash').textContent=money(state.portfolio.cash);$('#working').textContent=(total?invested/total*100:0).toFixed(1)+'%';const weighted=state.portfolio.positions.reduce((a,p)=>a+riskScore(p)*concentration(p),0)/100;$('#risk').textContent=Math.round(weighted)+'/100'}
function renderPortfolio(){const tbody=$('#portfolioBody');tbody.innerHTML='';state.portfolio.positions.forEach(p=>{const d=decision(p),tr=document.createElement('tr');tr.innerHTML=`<td><b>${p.symbol}</b><div class="muted">${p.account}</div></td><td>${p.qty}</td><td>${money(p.avg)}</td><td>${money(p.price)}</td><td class="${pnl(p)>=0?'green':'red'}">${money(pnl(p))}<div>${pct(p).toFixed(1)}%</div></td><td>${concentration(p).toFixed(1)}%</td><td>${healthScore(p)}</td><td>${opportunityScore(p)}</td><td>${riskScore(p)}</td><td>${cei(p)}</td><td class="action ${d.cls}">${d.label}</td>`;tbody.appendChild(tr)})}
function renderClassifications(){$('#watchlist').innerHTML=(state.portfolio.watchlist||[]).map(x=>`<div class="order"><strong>${x.symbol}</strong><span class="muted">${x.reason}</span></div>`).join('')||'<div class="notice">لا توجد أصول مراقبة.</div>';$('#memory').innerHTML=(state.portfolio.portfolio_memory||[]).map(x=>`<div class="order"><strong>${x.symbol} — ${x.event}</strong><span class="muted">${x.note||''}</span></div>`).join('')||'<div class="notice">لا توجد ذاكرة تخارج.</div>'}
function renderManagers(){$('#managers').innerHTML=(state.runtime.managers||[]).map(m=>`<div class="manager" data-manager="${m.id}"><b>${m.name}</b><div class="muted">${m.mission||''}</div><div class="status">جاهز</div></div>`).join('')}
function capitalPlan(){const cash=Number(state.portfolio.cash||0);return[['فرص قريبة مشروطة',35],['فرص متوسطة',20],['Income & DRIP',15],['صندوق الثروة',10],['احتياطي تكتيكي',20]].map(([name,pct])=>({name,pct,amount:cash*pct/100}))}
function renderCapital(){const html=capitalPlan().map(x=>`<div style="margin:11px 0"><div style="display:flex;justify-content:space-between"><span>${x.name}</span><b>${money(x.amount)}</b></div><div class="progress"><i style="width:${x.pct}%"></i></div></div>`).join('');$('#capitalBars').innerHTML=html;$('#capitalBars2').innerHTML=html}
function buildResearch(){const ps=state.portfolio.positions;const ranked=[...ps].sort((a,b)=>cei(b)-cei(a));state.opportunities=[{title:`أفضل مركز حالي بالكفاءة: ${ranked[0]?.symbol||'—'}`,body:`CEI ${ranked[0]?cei(ranked[0]):0}/100 — للمقارنة وليس أمر شراء.`},{title:'Watchlist: UEC',body:'غير مملوك. لا إعادة دخول إلا بمحفز خاص واختراق مؤكد وحجم تداول متوافق من أكثر من مصدر.'},{title:'بحث سوقي مطلوب',body:'AI Infrastructure، الطاقة النووية، DRIP الشرعي، والفرص منخفضة الارتباط بالمحفظة.'}];state.rnd=[{title:'تحسين جودة البيانات',body:'إضافة ختم وقت ومصدر لكل سعر وخبر ومنع القرار عند غياب التحقق.'},{title:'Academy Engine',body:'حفظ القرار والنتيجة ومقارنة توقع كل مدير بما حدث فعليًا.'},{title:'Capital Efficiency',body:'مقارنة كل مركز بفرصة بديلة قبل أي تعزيز أو احتفاظ.'}]}
function renderResearch(){if(!state.opportunities.length)buildResearch();$('#opportunities').innerHTML=state.opportunities.map(x=>`<div class="order"><strong>${x.title}</strong><span class="muted">${x.body}</span></div>`).join('');$('#rndQueue').innerHTML=state.rnd.map(x=>`<div class="order"><strong>${x.title}</strong><span class="muted">${x.body}</span></div>`).join('')}
function buildOrders(){const ps=state.portfolio.positions,nxb=ps.find(x=>x.symbol==='NXB'),eu=ps.find(x=>x.symbol==='EU'),best=[...ps].sort((a,b)=>cei(b)-cei(a))[0];state.orders=[{title:'قرار السيولة',body:`اعتماد ${money(state.portfolio.cash)} كسيولة مؤكدة. لا توظيف كامل؛ التقسيم ظاهر في Capital Rotation.`},{title:'NXB — دفاع رأسمالي',body:nxb?`Risk ${riskScore(nxb)}/100 وCEI ${cei(nxb)}/100. لا زيادة، وأي تخفيف يجب أن يحدد وجهة السيولة.`:'غير موجود كمركز حالي.'},{title:'EU — مراقبة التركّز',body:eu?`التركيز ${concentration(eu).toFixed(1)}%. يمنع التعزيز حتى يتحسن التركّز والعائد المعدل بالمخاطر.`:'غير موجود كمركز حالي.'},{title:'أولوية المقارنة',body:`أعلى CEI حاليًا: ${best?.symbol||'—'} (${best?cei(best):0}/100). هذا ترتيب داخلي لا توصية تنفيذ.`},{title:'UEC — تصنيف صحيح',body:'Portfolio Memory / Watchlist فقط. ليس مركزًا حاليًا ولا يدخل في الحسابات.'}]}
async function runBoard(){state.orders=[];state.logs=[];state.opportunities=[];state.rnd=[];renderOrders();$('#runBtn').disabled=true;const managers=state.runtime.managers||[];for(const m of managers){const card=$(`[data-manager="${m.id}"]`);if(card){card.classList.remove('done');card.classList.add('running');card.querySelector('.status').textContent='يعمل الآن'}log(`${m.name}: بدأ تنفيذ المهمة.`,'cyan');await sleep(280);if(m.id==='RND'){buildResearch();log('تم إنتاج بنك فرص أولي وطابور تطوير للمنصة.')}if(m.id==='OPP')log('تمت مقارنة المراكز الحالية حسب Opportunity Score وCEI.');if(m.id==='RISK'){const h=[...state.portfolio.positions].sort((a,b)=>riskScore(b)-riskScore(a))[0];log(`أعلى مخاطرة: ${h?.symbol||'—'} بدرجة ${h?riskScore(h):0}/100.`,'amber')}if(m.id==='CAP')log(`تم توزيع ${money(state.portfolio.cash)} على خمس مهام رأسمالية دون تجميد.`);if(m.id==='PORT')log('تم فصل Current Holdings عن Watchlist وPortfolio Memory.');if(m.id==='MACRO')log('لا توجد بيانات حية موثقة داخل هذه النسخة؛ تم منع ادعاء تحديث لحظي.','amber');if(m.id==='NEWS')log('محرك الأخبار في وضع انتظار مصدر موثوق؛ لا قرار من خبر غير متحقق.');if(m.id==='AUDIT'){const bad=state.portfolio.positions.some(x=>x.symbol==='UEC');log(bad?'خطأ: UEC ظهر كمركز حالي.':'نجح التدقيق: UEC غير موجود ضمن Current Holdings.',bad?'red':'green')}if(m.id==='CEO'){buildOrders();state.session={id:'OP-'+Date.now(),started:new Date().toISOString(),cash:state.portfolio.cash,total_assets:totalAssets(),orders:state.orders};log('اعتمد CEO القرار النهائي وأغلق الجلسة.','green')}if(card){card.classList.remove('running');card.classList.add('done');card.querySelector('.status').textContent='اكتمل'}}$('#runBtn').disabled=false;renderAll()}
function renderOrders(){$('#orders').innerHTML=state.orders.length?state.orders.map(o=>`<div class="order"><strong>${o.title}</strong><span class="muted">${o.body}</span></div>`).join(''):'<div class="notice">اضغط «تشغيل مجلس المديرين» لبدء جلسة جديدة من بيانات JSON الحالية.</div>'}
function exportJSON(){const blob=new Blob([JSON.stringify({session:state.session,portfolio:state.portfolio,orders:state.orders,opportunities:state.opportunities,rnd:state.rnd,logs:state.logs},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='omega-session-'+Date.now()+'.json';a.click();URL.revokeObjectURL(a.href)}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.add('hidden'));$('#'+b.dataset.view).classList.remove('hidden')});
$('#runBtn').onclick=runBoard;$('#exportBtn').onclick=exportJSON;loadData();
